#### open with RAYTRACER 
/vis/open RayTracer 
/vis/verbose errors


# Specify view angle:
/vis/viewer/set/viewpointThetaPhi 45. 135.
# Specify zoom value:
/vis/viewer/zoom 1.
# Define Up Vector
/vis/viewer/set/upVector 0 0 1

#/vis/rayTracer/eyePosition -100 -100 100 m
#/vis/rayTracer/lightDirection 1 -1 -1 
#/vis/rayTracer/target 0 0 0 m

/vis/rayTracer/column 1280
/vis/rayTracer/row 1280
/vis/rayTracer/span 2

# Draw geometry:
/vis/drawVolume
/vis/viewer/flush


